---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        supplementalGroups: [999,101,1000]
        fsGroup: 999
          #runAsUser: 999
          #runAsGroup: 999
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: tls-certs
              mountPath: /tls
              readOnly: true
            - name: tls-conf
              mountPath: /conf
              readOnly: false
          args:
            - -c
            - config_file=/conf/postgresql.conf
            - -c
            - hba_file=/conf/pg_hba.conf
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
      volumes:
        - name: tls-certs
          secret:
            secretName: postgresql-tls-secret
            defaultMode: 0640
        - name: tls-conf
          configMap:
            name: postgresql-conf

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: sandbox
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32345
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-conf
  namespace: sandbox
data:
  postgresql.conf: |
    listen_addresses = '*'
    shared_buffers = 256MB
    ssl = on
    ssl_ca_file = '/tls/ca.crt'
    ssl_cert_file = '/tls/tls.crt'
    ssl_key_file = '/tls/tls.key'
  pg_hba.conf: |
    local   all             all                                     trust
    hostssl all             all             0.0.0.0/0               trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
    host all all all scram-sha-256

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-tls
  namespace: sandbox
spec:
  secretName: postgresql-tls-secret
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - "postgresql-service.sandbox.svc.cluster.local"
    - "postgresql-service"
  issuerRef:
    name: root-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: postgresql-tls
  secretTemplate:
    labels:
      "app": "postgresql"

