---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: sandbox
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca-cert
  namespace: sandbox
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: true
  subject:
    organizations:
      - Example Inc.
    organizationalUnits:
      - DevOps
  dnsNames:
    - "root-ca.sandbox.svc.cluster.local"
    - "root-ca"
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: root-ca
  namespace: sandbox
spec:
  ca:
    secretName: root-ca-secret

